import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { AOSInit } from "@/lib/aos";
import "swiper/css";
import "swiper/css/pagination";

// const inter = Inter({ subsets: [] });

export const metadata: Metadata = {
  title: "Corporate",
  description: "Generated by Corporate",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AOSInit />
      <body>{children}</body>
    </html>
  );
}
