import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { AOSInit } from "@/lib/aos";

// const inter = Inter({ subsets: [] });

export const metadata: Metadata = {
  title: "Corporate",
  description: "Generated by Corporate",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AOSInit />
      <body >{children}</body>
    </html>
  );
}
